package eu.europa.ec.dgc.validation.restapi.dto;

import javax.validation.constraints.NotNull;
import lombok.Data;

@Data
public class ValidationInitRequest {
    /**
     * ECDSA key generated by the
     * user/wallet.
     */
    @NotNull
    private String pubKey;
    /**
     * Subject Value generated by the
     * Service backend.
     */
    @NotNull
    private String subject;
}
