package eu.europa.ec.dgc.validation.restapi.dto;

import javax.validation.constraints.NotNull;
import lombok.Data;

@Data
public class ValidationInitRequest {
    /**
     * ECDSA key generated by the
     * user/wallet.
     */
    @NotNull
    private String pubKey;
    /**
     * Use Crypto Metod accoding to JWT definitions in RFC7518.
     * ES256/PS256/RS256
     */
    @NotNull
    private String keyType;
    /**
     * Optional callback URL.
     */
    private String callback;
    
    @NotNull
    private String nonce;
}
