package eu.europa.ec.dgc.validation.entity;

import lombok.Data;

@Data
public class ValidationInquiry {
    public enum ValidationStatus { OPEN, READY }

    private String subject;
    private ValidationStatus validationStatus;
    private String validationResult;
    /**
     * key generated by verifier app used to sign the dcc
     */
    private String publicKey;
    private String keyType;
    private String callbackUrl;
    private long exp;
}
